document.writeln("<link type=\"text/css\" rel=\"stylesheet\" href=\"http://www.cssmoban.com/statics/css/astyle.css\" />");
document.writeln("<div align=\"center\">");
document.writeln("<script async src=\'//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\'></script>");
document.writeln("<ins class=\'adsbygoogle\'");
document.writeln("     style=\'display:block\'");
document.writeln("     data-ad-client=\'ca-pub-1542822386688301\'");
document.writeln("     data-ad-slot=\'5966457456\'");
document.writeln("     data-ad-format=\'auto\'></ins>");
document.writeln("<script>");
document.writeln("(adsbygoogle = window.adsbygoogle || []).push({});");
document.writeln("</script>");
document.writeln("</div>");